openapi: 3.0.1
info:
  title: '@jupiterone/graph-cisco-secure-workload'
  description: A JupiterOne Integration
  x-cortex-git:
    github:
      repository: JupiterOne/graph-cisco-secure-workload
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/graph-cisco-secure-workload'
